### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by YiranJing** [YiranJing/Lagardere_CommercialAnalysis#1]
@HarryYIM Please let me know if any error you find. And I will also check today.

**Comment by HarryYIM** [comment]
@YiranJing The first issue is that we still can see some entries relating to week2. It won't make sense based on the assumption (go against the rule of week2 selling nothing).

**Comment by YiranJing** [comment]
@HarryYIM Thansk has resolved. Please let me know more when you find :)
